name: Deploy example on now

on: [push]

jobs:
  deploy_example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test

      - name: Deploy example to now
        run: |
          cd example
          npm run docs
          npx now --token=${{ secrets.ZEIT_TOKEN }} --name=vuepress-jsdoc-example --prod
